"""add alerts notifications

Revision ID: 8ec94a38e7f4
Revises: c8ce14e1e339
Create Date: 2026-01-29 16:26:44.331032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec94a38e7f4'
down_revision: Union[str, Sequence[str], None] = 'c8ce14e1e339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('notification_sent', sa.Boolean(), nullable=False))
    op.add_column('alerts', sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('notification_channel', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('last_error', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'last_error')
    op.drop_column('alerts', 'notification_channel')
    op.drop_column('alerts', 'notification_sent_at')
    op.drop_column('alerts', 'notification_sent')
    # ### end Alembic commands ###
