"""add location_id to movements and thresholds

Revision ID: 3373e6b81640
Revises: 6f8657d8911f
Create Date: 2026-02-01 03:44:43.913508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3373e6b81640'
down_revision: Union[str, Sequence[str], None] = '6f8657d8911f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_index('ix_movements_location', 'movements', ['location_id'], unique=False)
    op.create_foreign_key(None, 'movements', 'locations', ['location_id'], ['id'])
    op.add_column('stock_thresholds', sa.Column('location_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_thresholds_location'), table_name='stock_thresholds')
    op.create_index('ix_thresholds_location', 'stock_thresholds', ['location_id'], unique=False)
    op.create_foreign_key(None, 'stock_thresholds', 'locations', ['location_id'], ['id'])
    op.drop_column('stock_thresholds', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_thresholds', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock_thresholds', type_='foreignkey')
    op.drop_index('ix_thresholds_location', table_name='stock_thresholds')
    op.create_index(op.f('ix_thresholds_location'), 'stock_thresholds', ['location'], unique=False)
    op.drop_column('stock_thresholds', 'location_id')
    op.drop_constraint(None, 'movements', type_='foreignkey')
    op.drop_index('ix_movements_location', table_name='movements')
    op.drop_column('movements', 'location_id')
    # ### end Alembic commands ###
