"""add locations

Revision ID: c51f9fca7313
Revises: 8ec94a38e7f4
Create Date: 2026-01-29 17:07:55.040488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51f9fca7313'
down_revision: Union[str, Sequence[str], None] = '8ec94a38e7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_locations_code', 'locations', ['code'], unique=False)
    op.add_column('events', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_index('ix_events_location', 'events', ['location_id'], unique=False)
    op.create_foreign_key(None, 'events', 'locations', ['location_id'], ['id'])
    op.add_column('stocks', sa.Column('location_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_stocks_location'), table_name='stocks')
    op.create_index('ix_stocks_location', 'stocks', ['location_id'], unique=False)
    op.create_foreign_key(None, 'stocks', 'locations', ['location_id'], ['id'])
    op.drop_column('stocks', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_index('ix_stocks_location', table_name='stocks')
    op.create_index(op.f('ix_stocks_location'), 'stocks', ['location'], unique=False)
    op.drop_column('stocks', 'location_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index('ix_events_location', table_name='events')
    op.drop_column('events', 'location_id')
    op.drop_index('ix_locations_code', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
