"""add indexes

Revision ID: c8ce14e1e339
Revises: 9e75fa04121a
Create Date: 2026-01-29 11:43:32.741808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ce14e1e339'
down_revision: Union[str, Sequence[str], None] = '9e75fa04121a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alerts_created', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['alert_status'], unique=False)
    op.create_index('ix_alerts_stock', 'alerts', ['stock_id'], unique=False)
    op.create_index('ix_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity'], unique=False)
    op.create_index('ix_audit_user', 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index('ix_events_created', 'events', ['created_at'], unique=False)
    op.create_index('ix_events_idempotency', 'events', ['idempotency_key'], unique=False)
    op.create_index('ix_events_product', 'events', ['product_id'], unique=False)
    op.create_index('ix_events_status', 'events', ['event_status'], unique=False)
    op.create_index('ix_events_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_movements_created', 'movements', ['created_at'], unique=False)
    op.create_index('ix_movements_product', 'movements', ['product_id'], unique=False)
    op.create_index('ix_movements_type', 'movements', ['movement_type'], unique=False)
    op.create_index('ix_movements_user', 'movements', ['user_id'], unique=False)
    op.create_index('ix_products_active', 'products', ['active'], unique=False)
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    op.create_index('ix_products_category', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_thresholds_location', 'stock_thresholds', ['location'], unique=False)
    op.create_index('ix_thresholds_product', 'stock_thresholds', ['product_id'], unique=False)
    op.create_index('ix_stocks_location', 'stocks', ['location'], unique=False)
    op.create_index('ix_stocks_product', 'stocks', ['product_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_stocks_product', table_name='stocks')
    op.drop_index('ix_stocks_location', table_name='stocks')
    op.drop_index('ix_thresholds_product', table_name='stock_thresholds')
    op.drop_index('ix_thresholds_location', table_name='stock_thresholds')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_barcode', table_name='products')
    op.drop_index('ix_products_active', table_name='products')
    op.drop_index('ix_movements_user', table_name='movements')
    op.drop_index('ix_movements_type', table_name='movements')
    op.drop_index('ix_movements_product', table_name='movements')
    op.drop_index('ix_movements_created', table_name='movements')
    op.drop_index('ix_events_type', table_name='events')
    op.drop_index('ix_events_status', table_name='events')
    op.drop_index('ix_events_product', table_name='events')
    op.drop_index('ix_events_idempotency', table_name='events')
    op.drop_index('ix_events_created', table_name='events')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_index('ix_audit_user', table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_created', table_name='audit_log')
    op.drop_index('ix_audit_action', table_name='audit_log')
    op.drop_index('ix_alerts_stock', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_created', table_name='alerts')
    # ### end Alembic commands ###
